AllCops:
  TargetRubyVersion: 2.3

Layout/LineLength:
  # defualt: 80
  Max: 160
  IgnoredPatterns:
    - '^\s*#'

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

